@@include('../../../frontend/bower_components/jquery/dist/jquery.min.js')
@@include('../../../frontend/bower_components/tether/dist/js/tether.min.js')
@@include('../../../frontend/bower_components/bootstrap/dist/js/bootstrap.min.js')
@@include('../../../frontend/bower_components/owl.carousel/dist/owl.carousel.min.js')
@@include('../../../frontend/bower_components/fancybox/dist/jquery.fancybox.min.js')
